//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_masterFuelStation
    {
        public int stationID { get; set; }
        public string stationname { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
